/*
export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";
 */

export const SET_ID_APPUSER = "SET_ID_APPUSER";
export const SET_APPUSER = "SET_APPUSER";
export const SET_ID_SHIFT = "SET_ID_SHIFT";
export const SET_ID_WAREHOUSE = "SET_ID_WAREHOUSE";

export const SET_MODULE = "SET_MODULE";

export const SET_SHIFT = "SET_SHIFT";
export const OPEN_SHIFT = "OPEN_SHIFT";
export const CLOSE_SHIFT = "CLOSE_SHIFT";
export const SET_DURATION = "SET_DURATION";
export const INCREASE_SALE_COUNT = "INCREASE_SALE_COUNT";

export const SET_NAME_ID_HASHMAP = "SET_NAME_ID_HASHMAP";
export const SET_CLIENT_DATA = "SET_CLIENT_DATA";
export const SET_BILLNAME_ARRAY = "SET_BILLNAME_ARRAY";
export const SET_CLIENT_NIT_ARRAY = "SET_CLIENT_NIT_ARRAY";
export const SET_NIT_CLIENT_HASHMAP = "SET_NIT_CLIENT_HASHMAP";
export const INCRESE_CLIENT_SALE_COUNT = "INCRESE_CLIENT_SALE_COUNT";

export const SET_ITEM_QUANTITY = "SET_ITEM_QUANTITY";
export const SET_ITEM_QUANTITY_CODE = "SET_ITEM_QUANTITY_CODE";
export const SET_WAREHOUSE = "SET_WAREHOUSE";

export const SET_COMPANY = "SET_COMPANY";
export const INCREASE_COMPANY_SALE_COUNT = "INCREASE_COMPANY_SALE_COUNT";

export const SET_CURRENCY = "SET_CURRENCY";
